const test=require('node:test'),assert=require('node:assert/strict'),C=require('../app/clinical.js'),R=require('../app/recovery.js');
const clinical=(extra={})=>({procedure:'icl',operated_eyes:'both',left_surgery_date:'2026-10-01',right_surgery_date:'2026-10-02',...extra});
function harness(){let n=0,quota=false;const data=new Map(),storage={getItem:k=>data.get(k)||null,setItem(k,v){if(quota)throw Error('quota');data.set(k,v);}};return{storage,store:R.createStore(storage,{makeId:()=>++n===1?'NV-TEST':'NV-'+n,now:()=>new Date('2026-10-02T02:00:00.000Z')}),fail:()=>quota=true};}
test('ICL and TICL include operated eyes and optional surgery dates',()=>{for(const procedure of ['icl','ticl'])assert.equal(C.validate(clinical({procedure}),'postop','2026-10-02').procedure,procedure);assert.match(C.summary(clinical(),'2026-10-02'),/左眼术后 1 天.*右眼术后 0 天/);assert.match(C.summary(null),/待填写/);C.validate(clinical({left_surgery_date:null,right_surgery_date:null}),'postop','2026-10-02');});
test('calendar, future, eye and procedure inconsistencies are rejected',()=>{for(const extra of [{procedure:'lasik'},{operated_eyes:'none'},{left_surgery_date:'2026-02-30'},{right_surgery_date:'2026-10-03'},{operated_eyes:'left'},{left_surgery_date:'<script>'}])assert.throws(()=>C.validate(clinical(extra),'postop','2026-10-02'));assert.throws(()=>C.validate(clinical(),'healthy','2026-10-02'));assert.throws(()=>C.validate({...clinical(),unrecognized:true},'postop'));});
test('clinical metadata persists and keeps old v3 profile readable',()=>{const h=harness();assert.equal(h.store.context().clinical,null);h.store.saveClinical(clinical());assert.equal(h.store.snapshot().schema,R.SCHEMA_V4);assert.deepEqual(R.createStore(h.storage).context().clinical,clinical());assert.throws(()=>h.store.setAccess('healthy'),/ICL/);assert.deepEqual(h.store.context().clinical,clinical());});
test('clinical metadata export and legacy imports enrich without deleting prior detail',()=>{const a=harness(),b=harness(),legacy=a.store.exportJSON();a.store.saveClinical(clinical());assert.equal(b.store.importJSON(a.store.exportJSON()),1);assert.deepEqual(b.store.context().clinical,clinical());assert.equal(b.store.importJSON(legacy),0);assert.deepEqual(b.store.context().clinical,clinical());const bad=JSON.parse(a.store.exportJSON());bad.profiles[0].clinical.procedure='ticl';const before=b.store.exportJSON();assert.throws(()=>b.store.importJSON(JSON.stringify(bad)));assert.equal(b.store.exportJSON(),before);});
test('clinical save remains atomic on storage failure and invalid fields',()=>{const h=harness(),before=h.store.exportJSON();h.fail();assert.throws(()=>h.store.saveClinical(clinical()),/存储不可用/);assert.equal(h.store.exportJSON(),before);assert.throws(()=>h.store.saveClinical(clinical({procedure:'unknown'})));assert.equal(h.store.exportJSON(),before);});
test('profile and snapshot clinical forms have distinct identifiers and escape date values',()=>{const a=C.form(clinical(),'postop'),b=C.form(clinical(),'postop','profile');assert.match(a,/id="ns-procedure"/);assert.match(b,/id="profile-procedure"/);assert.doesNotMatch(b,/id="ns-/);assert.doesNotMatch(C.form(clinical({left_surgery_date:'\"><script>bad</script>'}),'postop'),/<script>/);});
