const test=require('node:test'),assert=require('node:assert/strict'),R=require('../app/recovery.js'),{stoppedFixture}=require('../qa/v0.7.0-independent.cjs');
function harness(owner='NV-new-browser'){let fail=false,n=0;const map=new Map(),storage={getItem:k=>map.get(k)||null,setItem:(k,v)=>{if(fail)throw Error('quota');map.set(k,v);}};return {storage,store:R.createStore(storage,{makeId:p=>p==='NV'&&!n++?owner:p+'-'+n,now:()=>new Date('2026-10-02T12:00:00.000Z')}),fail:()=>fail=true};}
test('single downloaded training restores the original owner in a new browser with unknown clinical fields',()=>{const h=harness(),r=stoppedFixture();assert.equal(h.store.importJSON(JSON.stringify(r)),2);const state=h.store.snapshot();assert.equal(state.schema,R.SCHEMA_V7);assert.equal(state.active_participant_id,'NV-new-browser');assert.deepEqual(state.practice_sessions,JSON.parse(JSON.stringify([r])));const person=state.profiles.find(p=>p.participant_id===r.participant_id);assert.equal(person.access,'postop');assert.equal(person.clinical,undefined);assert.equal(person.created_at,'2026-10-02T12:00:00.000Z');h.store.switchProfile(r.participant_id);assert.equal(h.store.practiceHistory().length,1);assert.deepEqual(R.createStore(h.storage).snapshot(),h.store.snapshot());});
test('reimport is idempotent and conflicting single records fail without mutations',()=>{const h=harness(),r=stoppedFixture();h.store.importJSON(JSON.stringify(r));const before=h.store.exportJSON();assert.equal(h.store.importJSON(JSON.stringify(r)),0);assert.throws(()=>h.store.importJSON(JSON.stringify({...r,feedback:'noticeable'})),/不同内容/);assert.equal(h.store.exportJSON(),before);});
test('failed cross-browser restore cannot partially create a new profile',()=>{const h=harness(),r=stoppedFixture(),before=h.store.exportJSON();h.fail();assert.throws(()=>h.store.importJSON(JSON.stringify(r)));assert.equal(h.store.exportJSON(),before);});
test('whole backups retain practice sessions when older clinical backups are merged',()=>{const h=harness(),older=h.store.exportJSON(),r=stoppedFixture();h.store.importJSON(JSON.stringify(r));const before=h.store.exportJSON();h.store.importJSON(older);assert.equal(h.store.exportJSON(),before);assert.equal(h.store.snapshot().schema,R.SCHEMA_V7);});
test('training cannot be restored into an existing healthy-person identity',()=>{const r=stoppedFixture(),h=harness(r.participant_id);h.store.setAccess('healthy');const before=h.store.exportJSON();assert.throws(()=>h.store.importJSON(JSON.stringify(r)),/身份不一致/);assert.equal(h.store.exportJSON(),before);});

test('a restored placeholder can receive the original full clinical backup without losing the training',()=>{const r=stoppedFixture(),original=harness(r.participant_id),recovered=harness();original.store.saveClinical({procedure:'icl',operated_eyes:'both',left_surgery_date:'2026-09-01',right_surgery_date:'2026-09-01'});const old=JSON.parse(original.store.exportJSON());old.profiles[0].created_at='2026-09-01T10:00:00.000Z';recovered.store.importJSON(JSON.stringify(r));assert.equal(recovered.store.snapshot().profiles.find(p=>p.participant_id===r.participant_id).restored_from_practice,true);recovered.store.importJSON(JSON.stringify(old));const person=recovered.store.snapshot().profiles.find(p=>p.participant_id===r.participant_id);assert.equal(person.created_at,old.profiles[0].created_at);assert.equal(person.restored_from_practice,undefined);assert.deepEqual(person.clinical,old.profiles[0].clinical);assert.equal(recovered.store.snapshot().practice_sessions.length,1);});
