const test=require('node:test'),assert=require('node:assert/strict'),P=require('../app/training-plan.js');
function base(){return {now:'2026-10-02T12:00:00.000Z',context:{participant_id:'p1',access:'postop',clinical:{procedure:'icl',operated_eyes:'both',left_surgery_date:'2026-09-01',right_surgery_date:'2026-09-02'}},care:{id:'c1',participant_id:'p1',created_at:'2026-09-30T10:00:00.000Z',clearance:'reviewed',reviewed_on:'2026-09-30',symptoms:[],clinician_targets:['contrast']},reports:[],history:[],observations:[]};}
const session=(id,feedback='comfortable')=>({id,participant_id:'p1',source_care_id:'c1',created_at:id==='1'?'2026-09-30T11:00:00.000Z':'2026-10-01T11:00:00.000Z',completed_at:id==='1'?'2026-09-30T11:02:00.000Z':'2026-10-01T11:02:00.000Z',status:'complete',feedback,active_ms:120000,valid_trial_count:48,correct_count:40,blocks:['contrast','multiscale'].map(task_id=>({task_id,trials:Array.from({length:24},(_,i)=>({valid:true,correct:i%6!==0,familiarization:i<6,exposure_ms:i<6?500:200,cpd:task_id==='multiscale'?[1.5,3,6][i%3]:3}))}))});
test('ICL dates and postoperative clearance determine eligibility without assuming absent personal values',()=>{
 const b=base();assert.equal(P.build(b).status,'ready');delete b.context.clinical.left_surgery_date;assert.equal(P.build(b).status,'needs_data');b.context.clinical.left_surgery_date='2026-10-01';assert.equal(P.build(b).status,'needs_review');b.care.reviewed_on='2026-10-02';assert.equal(P.build(b).status,'ready');
});
test('current profile ownership, target and binocular concern are respected',()=>{for(const mutate of [b=>b.care.participant_id='p2',b=>b.care.clinician_targets=['accommodation'],b=>b.care.symptoms=['double']]){const b=base();mutate(b);assert.equal(P.build(b).status,'needs_review');}});
test('early or uncomfortable sessions use short budgets; two separate days with cross-scale practice introduce optional contexts with unchanged ceiling',()=>{
 const b=base();assert.equal(P.build(b).total_seconds,120);b.history=[session('1'),session('2')];assert.equal(P.build(b).total_seconds,240);assert.equal(P.build(b).items[1].task_id,'collinear');b.care.symptoms=['near'];assert.equal(P.build(b).total_seconds,120);assert.equal(P.build(b).items[1].task_id,'multiscale');
});
test('discomfort requires subsequent review; high score never overrides it',()=>{const b=base();b.history=[{...session('1','stop'),stop_reason:'discomfort'}];assert.equal(P.build(b).status,'needs_review');b.care.created_at='2026-10-02T02:00:00.000Z';b.care.reviewed_on='2026-10-02';assert.equal(P.build(b).status,'ready');});
test('uncertain feedback and invalid or insufficient trials cannot enable extensions',()=>{for(const change of [{feedback:'unreported'},{valid_trial_count:5,correct_count:5},{status:'stopped'},{correct_count:10}]){const b=base();b.history=[session('1'),{...session('2'),...change}];assert.equal(P.build(b).items[1].task_id,'multiscale');}});
test('reports preserve postoperative chronology and conflicting source values',()=>{const b=base(),r={id:'r1',participant_id:'p1',stage:'postop',created_at:'2026-09-15T12:00:00.000Z',exam_date:'2026-09-15',values:[{eye:'left',field:'vault',value:500}]};b.reports=[r,{...r,id:'r2',values:[{eye:'left',field:'vault',value:600}]}];assert.equal(P.build(b).status,'needs_data');b.reports=[{...r,exam_date:'2026-08-01'}];assert.equal(P.build(b).status,'needs_data');});
test('changing vault, IOP, myopic power or acuity does not fabricate an effective training dose',()=>{const b=base(),baseline=P.build(b);for(const field of ['vault','iop','sph','acuity_logmar'])for(const value of [0,10,100]){b.reports=[{id:'r1',participant_id:'p1',stage:'postop',created_at:'2026-09-15T12:00:00.000Z',exam_date:'2026-09-15',values:[{eye:'left',field,value}]}];const p=P.build(b);assert.equal(p.total_seconds,baseline.total_seconds);assert.deepEqual(p.items,baseline.items);}});
test('current stopped daily activity pauses, foreign-person and old activity do not affect allocation',()=>{const b=base();b.observations=[{participant_id:'p1',local_date:'2026-10-02',reading:'stopped'}];assert.equal(P.build(b).status,'needs_review');b.observations[0].participant_id='p2';assert.equal(P.build(b).status,'ready');b.observations[0].participant_id='p1';b.observations[0].local_date='2026-09-29';assert.equal(P.build(b).status,'ready');});
module.exports={base,session};

test('same-day repetition and missing scale coverage keep foundational practice',()=>{const b=base();b.history=[session('1'),session('2')];b.history[0].completed_at=b.history[1].completed_at;assert.equal(P.build(b).items[1].task_id,'multiscale');b.history=[session('1'),session('2')];for(const r of b.history)for(const t of r.blocks[1].trials)t.cpd=3;assert.equal(P.build(b).items[1].task_id,'multiscale');});
test('daily allocation includes saved and pending exposure once and respects remaining time',()=>{const b=base(),r={...session('3'),created_at:'2026-10-02T10:00:00.000Z',completed_at:'2026-10-02T10:02:00.000Z',active_ms:150000};b.history=[r];b.pending_practice=[r];let p=P.build(b);assert.equal(p.daily_used_seconds,150);assert.equal(p.total_seconds,90);r.active_ms=240000;assert.equal(P.build(b).status,'daily_complete');b.now='2026-10-03T12:00:00.000Z';assert.equal(P.build(b).status,'ready');});
test('recent care changes reset progression and context choice follows actual completed exposure',()=>{const b=base();b.history=[session('1'),session('2')];b.history[1].blocks.push({task_id:'collinear',trials:Array.from({length:15},()=>({valid:true,correct:true,familiarization:false,exposure_ms:200,cpd:3}))});assert.equal(P.build(b).items[1].task_id,'noise');b.care.id='new-care';assert.equal(P.build(b).items[1].task_id,'multiscale');});
